version: '3.8'

services:
  user-service:
    image: my-user-service:latest
    container_name: user-service-container
    ports:
      - "9092:9092"
    environment:
      - SERVER_PORT=9092
      - SPRING_APPLICATION_NAME=UserService
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-server:3306/user_ms
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - eureka-server
      - mysql-server

  eureka-server:
    image: your-eureka-image:tag
    container_name: eureka-server-container
    ports:
      - "8761:8761"

  mysql-server:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: user_ms
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
